enableVersioning: true
handle: financeTopics
name: 'Finance Topics'
propagationMethod: all
siteSettings:
  e3d3b33f-0a67-4e33-a28f-494d59801cf0:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'departments/finance/{slug}'
structure:
  maxLevels: null
  uid: 3ba51241-add9-445b-bc61-286f7fff3532
type: structure
